*WebDoc-test
aTest
	" `self foo` **is** *no good*. But `SmallInteger` is a very nice class but we can write it as well in Behavior or ClassDescription. _But_ __also__ do: and ifTrue:ifFalse: work.
	`//some faulty code should parser as well .` otherwise this sucks.
	More information can be found on http://www.pharo-project.org. 

Secont Topic
------------------

# Third Topic #
	
 1. go  
 2. not  
 3. there  

* go
* not
* there

"
	self foo.
	self class name.