uploaded
stcodeCss
	^ '
code {
	font-family: Monaco, Consolas, Courier;
	font-size: 14px;
}

code a {
	text-decoration: none;
}

.stIndent {
	margin-left: 3em;
}

.stReturn {
}

.stSelector {
	color: #005500;
}

.stInstanceVariable {
	color: #0000AA;
}

.stCharacterLiteral { 
    color: #663300
}

.stTempVariable {
	color: #6666BB;
}

.stSelf {
	color: #00AAAA;
}

.stSuper {
	color: #AA0000;
}

.stComment {
	color: #009900;
	font-family: Georgia, Serif;
	font-size: 15px;
}

.stFalse, .stTrue, .stNil {
    color: #660000;
}

'